language: cpp

os:
  - linux
  - osx

env:
  - BADGE=linux
  - BADGE=osx

# hack to get some OS-specific badges
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade cmake; fi
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script:
  - cmake --build . --target all
